spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: ENC(OUEEZ+LRbc7Qe0BlKpv5KlnrQSOyUQXEieqqK3S8357IeCTjYeJLvURX1NreC/Tj91T0y59bxfTNIZjPLeX0Pg1RZD32La7BGj36vJ/+HWHBM7k2u3eb/pvR8Yz5xUwvi5E8MeOVUvMSg4O0RvjUJg0JYrV9veZ+K+xqzgEIU5H9PrCetuPt0e1ADzp8+XLd)

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ENC(OUEEZ+LRbc7Qe0BlKpv5KlnrQSOyUQXEieqqK3S8357IeCTjYeJLvURX1NreC/Tj91T0y59bxfTNIZjPLeX0Pg1RZD32La7BGj36vJ/+HWHBM7k2u3eb/pvR8Yz5xUwvi5E8MeOVUvMSg4O0RvjUJg0JYrV9veZ+K+xqzgEIU5H9PrCetuPt0e1ADzp8+XLd)

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ENC(MaDwtgqXKfWsJDzgcIxnGk5BtJloti0ah+8nh9FrCEfLt4aih0x6DXRaafEvr7Lv4GRPa73YzlEcPATO+X5OeZr4p7YU918IiSjQW94HUmDFeGCdBJBCeuVkzXeFM8WyXq9ccZwFkRzLSrCotHGIVt6yR1UaF1JLqzQF1sNzS/WSQ4nqu2B7WZKrPyQeKFIE)
