spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: ENC(IQcA7jlFMGT1To24aRp3X2rXhXrUZnPU/vHGSRLtVa1QBJVZWpQkNWKrJk2v8aAemKIbcq/pJ+1jBod+0HpSSndIgKtDvEDPX6St1DIkAMg2H57sZUceq/sltI+XCAyiDkqyAin25eIkwQQCy99O/mH8abrSL7sXjx5XUOGa0ns=)

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ENC(IQcA7jlFMGT1To24aRp3X2rXhXrUZnPU/vHGSRLtVa1QBJVZWpQkNWKrJk2v8aAemKIbcq/pJ+1jBod+0HpSSndIgKtDvEDPX6St1DIkAMg2H57sZUceq/sltI+XCAyiDkqyAin25eIkwQQCy99O/mH8abrSL7sXjx5XUOGa0ns=)

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ENC(IQcA7jlFMGT1To24aRp3X2rXhXrUZnPU/vHGSRLtVa1QBJVZWpQkNWKrJk2v8aAemKIbcq/pJ+1jBod+0HpSSndIgKtDvEDPX6St1DIkAMg2H57sZUceq/sltI+XCAyiDkqyAin25eIkwQQCy99O/mH8abrSL7sXjx5XUOGa0ns=)
